services:
  parakeet:
    build: .
    container_name: parakeet-stt
    ports:
      - "8000:8000"
    # env_file: .env               # TODO
    environment:
      LOG_LEVEL: "INFO"
    volumes:
      - ./data/cache:/root/.cache
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "4"
    #       memory: 4G
    restart: unless-stopped
