#!/usr/bin/env bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --no-install-recommends \
  build-essential git cmake pkg-config wget curl ca-certificates \
  libssl-dev zlib1g-dev libsndfile1 libsndfile1-dev libasound2-dev \
  python3 python3-venv python3-pip tmux numactl psmisc

# (Optional) keep GPU persistent clocks/session
command -v nvidia-smi >/dev/null && nvidia-smi -pm 1 || true

# Get sherpa-onnx
cd /opt
[ -d sherpa-onnx ] || git clone https://github.com/k2-fsa/sherpa-onnx.git
cd sherpa-onnx

# Build (GPU + WebSocket binaries are generated by default)
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DSHERPA_ONNX_ENABLE_GPU=ON ..
make -j"$(nproc)"

echo "Binaries in: $(pwd)/bin (e.g., sherpa-onnx-online-websocket-server)"
