#!/usr/bin/env bash
# High-performance environment for Parakeet ASR service.
# Optimized for high concurrency (100+ requests) with mixed short/long audio.

export HOST=${HOST:-0.0.0.0}
export PORT=${PORT:-8000}

# GPU + scheduling (optimized for high concurrency + mixed short/long audio)
export PARAKEET_QUEUE_MAX_FACTOR=${PARAKEET_QUEUE_MAX_FACTOR:-64}
export PARAKEET_MAX_QUEUE_WAIT_S=${PARAKEET_MAX_QUEUE_WAIT_S:-2}
export PARAKEET_MICROBATCH_WINDOW_MS=${PARAKEET_MICROBATCH_WINDOW_MS:-15}
export PARAKEET_MICROBATCH_MAX_BATCH=${PARAKEET_MICROBATCH_MAX_BATCH:-64}

# Duration-aware inference timeout system (210s max audio, 1.3x worst-case xRT)
# Base infer = 210/1.3 = 161.5s; safety 1.5x => 242.3s; +2s queue => ~244s
export PARAKEET_EXPECTED_XRT_MIN=${PARAKEET_EXPECTED_XRT_MIN:-1.3}
export PARAKEET_INFER_TIMEOUT_SAFETY=${PARAKEET_INFER_TIMEOUT_SAFETY:-1.5}
export PARAKEET_INFER_TIMEOUT_CAP_S=${PARAKEET_INFER_TIMEOUT_CAP_S:-250}

# Limits
# Max single-audio duration (seconds). Extra audio is ignored (trimmed).
export PARAKEET_MAX_AUDIO_SECONDS=${PARAKEET_MAX_AUDIO_SECONDS:-210}
export PARAKEET_MAX_UPLOAD_MB=${PARAKEET_MAX_UPLOAD_MB:-64}

export PARAKEET_MODEL_ID=nvidia/parakeet-ctc-1.1b-v2
export PARAKEET_USE_LOCAL_ATTENTION=${PARAKEET_USE_LOCAL_ATTENTION:-1}
export PARAKEET_LOCAL_ATTENTION_CONTEXT=${PARAKEET_LOCAL_ATTENTION_CONTEXT:-128}
export PARAKEET_SUBSAMPLING_CHUNKING_FACTOR=${PARAKEET_SUBSAMPLING_CHUNKING_FACTOR:-1}

export PARAKEET_DEVICE_ID=${PARAKEET_DEVICE_ID:-0}

# GPU visibility and faster HF downloads
if [[ -z "${CUDA_VISIBLE_DEVICES:-}" ]]; then export CUDA_VISIBLE_DEVICES="${PARAKEET_DEVICE_ID}"; fi
export HF_HUB_ENABLE_HF_TRANSFER=${HF_HUB_ENABLE_HF_TRANSFER:-1}

# ASR perf knobs (optimized for high concurrency + GPU utilization)
export PARAKEET_ASR_BATCH_SIZE=${PARAKEET_ASR_BATCH_SIZE:-64}
export PARAKEET_ASR_NUM_WORKERS=${PARAKEET_ASR_NUM_WORKERS:-0}
export PARAKEET_USE_AUTOCAST=${PARAKEET_USE_AUTOCAST:-1}
export PARAKEET_AUTOCAST_DTYPE=${PARAKEET_AUTOCAST_DTYPE:-float16}
export PARAKEET_CUDNN_BENCHMARK=${PARAKEET_CUDNN_BENCHMARK:-1}

# CPU/GPU perf knobs
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-6}
export MKL_NUM_THREADS=${MKL_NUM_THREADS:-6}
export OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS:-6}
export CUDA_MODULE_LOADING=${CUDA_MODULE_LOADING:-LAZY}

# WebSocket tuning (explicit defaults for robustness)
export WS_MAX_SIZE=${WS_MAX_SIZE:-16777216}
export WS_PING_INTERVAL=${WS_PING_INTERVAL:-20}
export WS_PING_TIMEOUT=${WS_PING_TIMEOUT:-20}
