#!/usr/bin/env bash
# Default environment for Parakeet service. Edit as needed.

export HOST=${HOST:-0.0.0.0}
export PORT=${PORT:-8000}

# GPU + scheduling
export PARAKEET_QUEUE_MAX_FACTOR=${PARAKEET_QUEUE_MAX_FACTOR:-16}
export PARAKEET_MAX_QUEUE_WAIT_S=${PARAKEET_MAX_QUEUE_WAIT_S:-2}
export PARAKEET_MICROBATCH_WINDOW_MS=${PARAKEET_MICROBATCH_WINDOW_MS:-4}
export PARAKEET_MICROBATCH_MAX_BATCH=${PARAKEET_MICROBATCH_MAX_BATCH:-16}

# Limits
export PARAKEET_MAX_AUDIO_SECONDS=${PARAKEET_MAX_AUDIO_SECONDS:-600}
export PARAKEET_MAX_UPLOAD_MB=${PARAKEET_MAX_UPLOAD_MB:-64}

export PARAKEET_MODEL_ID=${PARAKEET_MODEL_ID:-nvidia/parakeet-ctc-0.6b}
export PARAKEET_USE_LOCAL_ATTENTION=${PARAKEET_USE_LOCAL_ATTENTION:-1}
export PARAKEET_LOCAL_ATTENTION_CONTEXT=${PARAKEET_LOCAL_ATTENTION_CONTEXT:-128}
export PARAKEET_SUBSAMPLING_CHUNKING_FACTOR=${PARAKEET_SUBSAMPLING_CHUNKING_FACTOR:-1}

export PARAKEET_DEVICE_ID=${PARAKEET_DEVICE_ID:-0}

# CPU/GPU perf knobs
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-6}
export MKL_NUM_THREADS=${MKL_NUM_THREADS:-6}
export OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS:-6}
export CUDA_MODULE_LOADING=${CUDA_MODULE_LOADING:-LAZY}
