#!/usr/bin/env bash
# High-performance environment for Parakeet ASR service.
# Optimized for high concurrency (100+ requests) with mixed short/long audio.

export HOST=${HOST:-0.0.0.0}
export PORT=${PORT:-8000}

# GPU + scheduling (optimized for high concurrency + mixed short/long audio)
export PARAKEET_QUEUE_MAX_FACTOR=${PARAKEET_QUEUE_MAX_FACTOR:-128}
export PARAKEET_MAX_QUEUE_WAIT_S=${PARAKEET_MAX_QUEUE_WAIT_S:-2}
export PARAKEET_MICROBATCH_WINDOW_MS=${PARAKEET_MICROBATCH_WINDOW_MS:-8}
export PARAKEET_MICROBATCH_MAX_BATCH=${PARAKEET_MICROBATCH_MAX_BATCH:-32}
# Single priority scheduler (no separate finals lane); generous finals timeout
export PARAKEET_FINALS_TIMEOUT_S=${PARAKEET_FINALS_TIMEOUT_S:-2.0}

# Duration-aware inference timeout system (210s max audio, 1.3x worst-case xRT)
# Base infer = 210/1.3 = 161.5s; safety 1.5x => 242.3s; +2s queue => ~244s
export PARAKEET_EXPECTED_XRT_MIN=${PARAKEET_EXPECTED_XRT_MIN:-1.3}
export PARAKEET_INFER_TIMEOUT_SAFETY=${PARAKEET_INFER_TIMEOUT_SAFETY:-1.5}
export PARAKEET_INFER_TIMEOUT_CAP_S=${PARAKEET_INFER_TIMEOUT_CAP_S:-250}

# Limits
# Max single-audio duration (seconds). Extra audio is ignored (trimmed).
export PARAKEET_MAX_AUDIO_SECONDS=${PARAKEET_MAX_AUDIO_SECONDS:-210}
export PARAKEET_MAX_UPLOAD_MB=${PARAKEET_MAX_UPLOAD_MB:-64}

export PARAKEET_MODEL_ID=nvidia/parakeet-tdt-0.6b-v2
export PARAKEET_USE_LOCAL_ATTENTION=${PARAKEET_USE_LOCAL_ATTENTION:-1}
export PARAKEET_LOCAL_ATTENTION_CONTEXT=${PARAKEET_LOCAL_ATTENTION_CONTEXT:-128}
export PARAKEET_SUBSAMPLING_CHUNKING_FACTOR=${PARAKEET_SUBSAMPLING_CHUNKING_FACTOR:-1}

export PARAKEET_DEVICE_ID=${PARAKEET_DEVICE_ID:-0}

# GPU visibility and faster HF downloads
if [[ -z "${CUDA_VISIBLE_DEVICES:-}" ]]; then export CUDA_VISIBLE_DEVICES="${PARAKEET_DEVICE_ID}"; fi
export HF_HUB_ENABLE_HF_TRANSFER=${HF_HUB_ENABLE_HF_TRANSFER:-1}

# ASR perf knobs (optimized for high concurrency + GPU utilization)
export PARAKEET_ASR_BATCH_SIZE=${PARAKEET_ASR_BATCH_SIZE:-32}
export PARAKEET_ASR_NUM_WORKERS=${PARAKEET_ASR_NUM_WORKERS:-0}
export PARAKEET_USE_AUTOCAST=${PARAKEET_USE_AUTOCAST:-1}
export PARAKEET_AUTOCAST_DTYPE=${PARAKEET_AUTOCAST_DTYPE:-float16}
export PARAKEET_CUDNN_BENCHMARK=${PARAKEET_CUDNN_BENCHMARK:-1}

# CPU/GPU perf knobs
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-6}
export MKL_NUM_THREADS=${MKL_NUM_THREADS:-6}
export OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS:-6}
export CUDA_MODULE_LOADING=${CUDA_MODULE_LOADING:-LAZY}

# gRPC streaming cadence and context
export PARAKEET_STREAM_STEP_MS=${PARAKEET_STREAM_STEP_MS:-240}
export PARAKEET_STREAM_CONTEXT_SECONDS=${PARAKEET_STREAM_CONTEXT_SECONDS:-5}
export PARAKEET_STREAM_TICK_TIMEOUT_S=${PARAKEET_STREAM_TICK_TIMEOUT_S:-0.6}
export PARAKEET_STREAM_HOT_QUEUE_FRACTION=${PARAKEET_STREAM_HOT_QUEUE_FRACTION:-0.85}
export PARAKEET_STREAM_DECIMATION_MIN_INTERVAL_MS=${PARAKEET_STREAM_DECIMATION_MIN_INTERVAL_MS:-200}
export PARAKEET_STREAM_DECIMATION_WHEN_HOT=${PARAKEET_STREAM_DECIMATION_WHEN_HOT:-1}

# TLS (optional)
export PARAKEET_GRPC_TLS=${PARAKEET_GRPC_TLS:-0}
export PARAKEET_GRPC_CERT=${PARAKEET_GRPC_CERT:-}
export PARAKEET_GRPC_KEY=${PARAKEET_GRPC_KEY:-}

# VAD and eager finalize knobs
export PARAKEET_VAD_ENABLE=${PARAKEET_VAD_ENABLE:-1}
export PARAKEET_VAD_TAIL_MS=${PARAKEET_VAD_TAIL_MS:-300}
export PARAKEET_VAD_ENERGY_THRESHOLD=${PARAKEET_VAD_ENERGY_THRESHOLD:-0.001}
export PARAKEET_EAGER_SIL_MS=${PARAKEET_EAGER_SIL_MS:-600}

# Segmentation knobs
export PARAKEET_SEGMENT_LEN_MS=${PARAKEET_SEGMENT_LEN_MS:-2500}
export PARAKEET_SEGMENT_MIN_MS=${PARAKEET_SEGMENT_MIN_MS:-1500}
export PARAKEET_SEGMENT_OVERLAP_MS=${PARAKEET_SEGMENT_OVERLAP_MS:-250}

# CUDA runtime (cudart) path helpers. Prepend common locations if present.
if [[ -d "/usr/local/cuda/lib64" ]]; then
  export LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH:-}"
fi
if [[ -d "/usr/local/cuda-12/lib64" ]]; then
  export LD_LIBRARY_PATH="/usr/local/cuda-12/lib64:${LD_LIBRARY_PATH:-}"
fi
if [[ -d "/usr/local/cuda-12.1/lib64" ]]; then
  export LD_LIBRARY_PATH="/usr/local/cuda-12.1/lib64:${LD_LIBRARY_PATH:-}"
fi
if [[ -d "/usr/lib/x86_64-linux-gnu" ]]; then
  export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH:-}"
fi
